name: Generate Documentation Reports
description: Report generator that takes multiple .md files from a source and combines them into a single .md file.

inputs:
  docs-path:
    required: true
    default: docs/
  output-path:
    required: true
    default: docs/report.md
  blacklist:
    required: false

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Generate reports
      run: |
        python ${{ github.action_path }}/src/report_generator.py \
          --docs ${{ inputs.docs-path }} \
          --output ${{ inputs.output-path }} \
          --blacklist "${{ inputs.blacklist-folders }}"