@startuml development_view

title BrokerX - Vue de développement

package "BrokerX" {
    package "Adapters" {
        package "Persistence" {}
    }

    package "Domain" {
        package "Models" {}
        package "Ports" {}
        package "Services" {}
    }
}

package "BrokerX.InstrumentService" {
    package "Adapters" {
        package "Persistence" {}
    }

    package "Domain" {
        package "Models" {}
        package "Ports" {}
        package "Services" {}
    }
}

package "BrokerX.PortfolioService" {
    package "Adapters" {
        package "Persistence" {}
    }

    package "Domain" {
        package "Models" {}
        package "Ports" {}
        package "Services" {}
    }
}

package "BrokerX.MatchingEngine" {
    package "Adapters" {
        package "Persistence" {}
    }

    package "Domain" {
        package "Models" {}
        package "Ports" {}
        package "Services" {}
    }
}

@enduml