@startuml execution_view

left to right direction

rectangle "Légende" {
  actor "Acteur" as L1
  usecase "Cas d'utilisation" as L2
}

:AC01 - Client: as client

package "Système" {
  (UC-01\nInscription & Vérification d’identité) as (UC01)
  (UC-02\nAuthentification & MFA) as (UC02)
  (UC-03\nApprovisionnement du portefeuille) as (UC03)
  (UC-04\nAbonnement aux données du marché) as (UC04)
  (UC-05\nPlacement d’un ordre) as (UC05)
  (UC-06\nModification/Annulation d'un ordre) as (UC06)
  (UC-07\nAppariement interne & Exécution) as (UC07)
  (UC-08\nConfirmation d’exécution & Notifications) as (UC08)
}

client --> (UC01)
client --> (UC02)
client --> (UC03)
client --> (UC04)
client --> (UC05)
client --> (UC06)

(UC02) ..> (UC01) : <<Inclus>>
(UC05) ..> (UC03) : <<Inclus>>
(UC06) ..> (UC05) : <<Inclus>>
(UC07) ..> (UC05) : <<Extension>>
(UC08) ..> (UC07) : <<Extension>>

@enduml