@startuml mdd
skinparam style strictuml
hide methods
hide empty members

title BrokerX - Modèle du domaine

class User {
    id: String
    firstName: String
    lastName: String
    birthday: String
    email: String
    phoneNumber: String
    address: String
    state: String
}
note left
    State peut être:
    - Pending
    - Active
    - Rejected
    - Suspended
end note

class Portfolio {
    balance: decimal
}

class Position {
    quantity: decimal
}

class Transaction {
    id: String
    fees: decimal
    totalAmount: decimal
    timestamp: String
    state: String
}
note right
    State peut être:
    - Pending
    - Settled
    - Failed
end note

class FundTransaction implements Transaction {}

class TradeTransaction implements Transaction {
    unitPrice: decimal
    quantity: decimal
}

class Deposit implements FundTransaction {}
class Withdrawal implements FundTransaction {}
class Settlement implements TradeTransaction {}
class Buy implements TradeTransaction {}
class Sell implements TradeTransaction {}

class OrderBook {}

class PreTradeControl {}
class PostTradeControl {}

class MatchingEngine {}

class Fill {
    id: String
    price: decimal
    quantity: decimal
    timestamp: String
}

class Order {
    id: String
    sens: String
    quantity: decimal
    state: String
}
note left
    Sens peut être:
    - Buy
    - Sell

    State peut être:
    - Pending
    - Working
    - Rejected
    - Cancelled
    - Filled
    - PartiallyFilled
    - Expired
end note

class MarketOrder implements Order {}
class LimitOrder implements Order {
    unitPrice: decimal
}

class OrderDuration {}
class DAYOrder implements OrderDuration {}
class GTCOrder implements OrderDuration {}
class IOCOrder implements OrderDuration {}
class FOKOrder implements OrderDuration {}
class GTDOrder implements OrderDuration {}

class Instrument {
    ticker: String
    name: String
}

class Quote {
    open: decimal
    high: decimal
    low: decimal
    close: decimal
    timestamp: String
}

class QuoteBook {}

User -- Portfolio : possède >
Portfolio -- "0..*" Position  : contient >
Portfolio -- "0..*" Transaction  : contient >
Transaction -- Instrument : référence >
Position -- Instrument : référence >

User "*" -- "*" Order : passe >

OrderBook -- "0..*" Order : contient >
Order -- OrderDuration : exécuté selon >
Order -- Instrument : référence >

PreTradeControl -- "*" Order : valide >
PostTradeControl == "*" Fill : valide >

MatchingEngine -- OrderBook : consulte >
MatchingEngine -- "*" Order : exécute >
(MatchingEngine, Order) -- Fill

QuoteBook -- "0..*" Quote : contient >
Quote "1..*" -- Instrument : décrit l'état >

@enduml